name: ðŸŒ² Create Cedar App Test

on:
  workflow_call:

jobs:
  create-cedar-app:
    runs-on: ubuntu-latest

    env:
      REDWOOD_CI: 1
      REDWOOD_DISABLE_TELEMETRY: 1

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Set up job
        uses: ./.github/actions/set-up-job

      - name: Set up test project
        run: |
          yarn build:pack
          PROJECT_PATH=$(yarn set-up-test-project)
          echo "PROJECT_PATH=$PROJECT_PATH" >> $GITHUB_ENV
        working-directory: ./packages/create-cedar-app
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Set up git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: e2e test
        run: yarn test:e2e
        working-directory: ./packages/create-cedar-app
        env:
          PROJECT_PATH: ${{ env.PROJECT_PATH }}

      - name: Install expect
        run: |
          sudo apt-get update
          sudo apt-get install expect

      - name: Prompt tests
        run: |
          ./tests/e2e_prompts.sh
          ./tests/e2e_prompts_git.sh
          ./tests/e2e_prompts_m.sh
          ./tests/e2e_prompts_ts.sh
          ./tests/e2e_prompts_overwrite.sh
        working-directory: ./packages/create-cedar-app
        env:
          PROJECT_PATH: ${{ env.PROJECT_PATH }}

      - name: â¬¢ Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 18

      - name: Prompt tests
        run: ./tests/e2e_prompts_node_less.sh
        working-directory: ./packages/create-cedar-app
        env:
          PROJECT_PATH: ${{ env.PROJECT_PATH }}

      - name: â¬¢ Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 21

      - name: Prompt tests
        run: ./tests/e2e_prompts_node_greater.sh
        working-directory: ./packages/create-cedar-app
        env:
          PROJECT_PATH: ${{ env.PROJECT_PATH }}
