name: ğŸ Publish Release Candidate

on:
  push:
    branches: ['release/**']
    # We don't want this to run on release
    tags-ignore: ['v**']
    # No need to run on docs-only changes
    paths-ignore: ['docs/**']

# Cancel in-progress runs of this workflow.
# See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  check-git-tags:
    name: ğŸ· Check git tags
    if: github.repository == 'cedarjs/cedar'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        # Required because lerna uses tags to determine the version.
        with:
          fetch-depth: 0

      - name: Enable Corepack
        run: npm install --global corepack

      - name: â¬¢ Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24

      - name: ğŸ· Check git tags
        run: |
          CURRENT_TAG=$(git describe --abbrev=0)

          # `github.ref_name` is something like `release/minor/v1.1.0`.
          # `basename` gets us `v1.1.0`
          BRANCH_TAG=$(basename ${{ github.ref_name }})

          echo
          echo "Current tag is $CURRENT_TAG"
          echo "Branch tag is $BRANCH_TAG"
          echo "Comparing tags with \"yarn dlx semver-compare-cli $CURRENT_TAG lt $BRANCH_TAG\""
          echo

          # See if the current tag is less than the branch's tag.
          # If it is, we're good to keep going.
          yarn dlx semver-compare-cli $CURRENT_TAG lt $BRANCH_TAG

  publish-release-candidate:
    name: ğŸš¢ Publish Release Candidate
    needs: check-git-tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          # `fetch-depth`â€”number of commits to fetch. `0` fetches all history for all branches and tags.
          #  This is required because lerna uses tags to determine the version.
          fetch-depth: 0

      - name: Set up job
        uses: ./.github/actions/set-up-job

      - name: ğŸ” Lint
        run: yarn lint

      - name: ğŸ§ª Test
        run: yarn test

      - name: ğŸš¢ Publish Release Candidate
        run: yarn tsx .github/scripts/publish-release-candidate.ts
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
